/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.twu.biblioteca;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;
import java.io.*;

public class AppTest {
    @Test public void testWelcomeMessage() {
        ByteArrayOutputStream bytes = new ByteArrayOutputStream();
        PrintStream console = System.out;
        try {
           System.setOut(new PrintStream(bytes));
           App.main(new String[0]);
        } finally {
           System.setOut(console);
        }
        assertEquals(String.format(
              "Welcome to Biblioteca. Your one-stop-shop for great book titles in Bangalore%n"),
              bytes.toString());
    }
}
